name: Deploy to Amazon ECS

on:
    push:
        branches: ['master']

env:
    AWS_REGION: us-east-1 # set this to your preferred AWS region, e.g. us-west-1

permissions:
    contents: read

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Install EB CLI
              run: |
                  sudo apt-get update
                  sudo apt-get install python3.7
                  curl -O https://bootstrap.pypa.io/get-pip.py
                  python3 get-pip.py --user
                  pip install awsebcli --upgrade --user
                  eb --version

            - name: Deploy to Elastic Beanstalk
              run: |
                  eb init --platform node.js --region us-east-2
                  eb create --sample pr3c10us
                  
            - name: Deploy to Elastic Beanstalk
              run: |
                git add .
                git commit -m "Deploy to Elastic Beanstalk"
                eb deploy 
